version: 2
updates:
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "06:00"
    reviewers:
      - "rsp2k"
    assignees:
      - "rsp2k"
    commit-message:
      prefix: "deps"
      include: "scope"
    open-pull-requests-limit: 5
    target-branch: "main"
    
  - package-ecosystem: "github-actions"
    directory: "/.github/workflows"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "06:00"
    reviewers:
      - "rsp2k"
    assignees:
      - "rsp2k"
    commit-message:
      prefix: "ci"
      include: "scope"
    open-pull-requests-limit: 3