"""Initial migration with project-based multi-tenant RBAC

Revision ID: 26acea1a5a8f
Revises: 
Create Date: 2025-09-24 06:33:04.301467

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '26acea1a5a8f'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('projects',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('slug', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('ACTIVE', 'SUSPENDED', 'ARCHIVED', name='projectstatus'), nullable=False),
    sa.Column('color', sa.String(length=7), nullable=True),
    sa.Column('avatar_url', sa.String(length=512), nullable=True),
    sa.Column('owner_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('settings', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug')
    )
    op.create_index('idx_projects_owner_id', 'projects', ['owner_id'], unique=False)
    op.create_index('idx_projects_slug', 'projects', ['slug'], unique=False)
    op.create_index('idx_projects_status', 'projects', ['status'], unique=False)
    op.create_table('project_audit_logs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('action', sa.String(length=100), nullable=False),
    sa.Column('resource_type', sa.String(length=50), nullable=False),
    sa.Column('resource_id', sa.String(length=255), nullable=True),
    sa.Column('resource_name', sa.String(length=255), nullable=True),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('user_agent', sa.Text(), nullable=True),
    sa.Column('old_values', sa.JSON(), nullable=True),
    sa.Column('new_values', sa.JSON(), nullable=True),
    sa.Column('context_data', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_audit_logs_action', 'project_audit_logs', ['action'], unique=False)
    op.create_index('idx_audit_logs_created_at', 'project_audit_logs', ['created_at'], unique=False)
    op.create_index('idx_audit_logs_project_id', 'project_audit_logs', ['project_id'], unique=False)
    op.create_index('idx_audit_logs_resource_type', 'project_audit_logs', ['resource_type'], unique=False)
    op.create_index('idx_audit_logs_user_id', 'project_audit_logs', ['user_id'], unique=False)
    op.create_table('project_invitations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('role', sa.Enum('OWNER', 'ADMIN', 'MANAGER', 'DEVELOPER', 'VIEWER', name='projectrole'), nullable=False),
    sa.Column('token', sa.String(length=255), nullable=False),
    sa.Column('accepted', sa.Boolean(), nullable=False),
    sa.Column('accepted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('accepted_by_user_id', sa.UUID(), nullable=True),
    sa.Column('invited_by_user_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['accepted_by_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['invited_by_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('project_id', 'email', name='uq_project_invitation_email'),
    sa.UniqueConstraint('token')
    )
    op.create_index('idx_project_invitations_email', 'project_invitations', ['email'], unique=False)
    op.create_index('idx_project_invitations_expires_at', 'project_invitations', ['expires_at'], unique=False)
    op.create_index('idx_project_invitations_project_id', 'project_invitations', ['project_id'], unique=False)
    op.create_index('idx_project_invitations_token', 'project_invitations', ['token'], unique=False)
    op.create_table('project_members',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('role', sa.Enum('OWNER', 'ADMIN', 'MANAGER', 'DEVELOPER', 'VIEWER', name='projectrole'), nullable=False),
    sa.Column('added_by_user_id', sa.UUID(), nullable=True),
    sa.Column('added_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['added_by_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('project_id', 'user_id', name='uq_project_user')
    )
    op.create_index('idx_project_members_project_id', 'project_members', ['project_id'], unique=False)
    op.create_index('idx_project_members_role', 'project_members', ['role'], unique=False)
    op.create_index('idx_project_members_user_id', 'project_members', ['user_id'], unique=False)
    op.add_column('managed_resources', sa.Column('project_id', sa.UUID(), nullable=False))
    op.create_index('idx_managed_resources_collection_id', 'managed_resources', ['service_collection_id'], unique=False)
    op.create_index('idx_managed_resources_name', 'managed_resources', ['resource_name'], unique=False)
    op.create_index('idx_managed_resources_project_id', 'managed_resources', ['project_id'], unique=False)
    op.create_index('idx_managed_resources_status', 'managed_resources', ['status'], unique=False)
    op.create_index('idx_managed_resources_type', 'managed_resources', ['resource_type'], unique=False)
    op.create_index('idx_managed_resources_vultr_id', 'managed_resources', ['vultr_resource_id'], unique=False)
    op.create_foreign_key(None, 'managed_resources', 'projects', ['project_id'], ['id'])
    op.add_column('planned_resources', sa.Column('project_id', sa.UUID(), nullable=False))
    op.create_index('idx_planned_resources_collection_id', 'planned_resources', ['service_collection_id'], unique=False)
    op.create_index('idx_planned_resources_name', 'planned_resources', ['resource_name'], unique=False)
    op.create_index('idx_planned_resources_project_id', 'planned_resources', ['project_id'], unique=False)
    op.create_index('idx_planned_resources_type', 'planned_resources', ['resource_type'], unique=False)
    op.create_foreign_key(None, 'planned_resources', 'projects', ['project_id'], ['id'])
    op.add_column('service_collections', sa.Column('project_id', sa.UUID(), nullable=False))
    op.create_foreign_key(None, 'service_collections', 'projects', ['project_id'], ['id'])
    op.add_column('workflow_operations', sa.Column('project_id', sa.UUID(), nullable=False))
    op.create_index('idx_workflow_operations_assigned_to', 'workflow_operations', ['assigned_to_id'], unique=False)
    op.create_index('idx_workflow_operations_collection_id', 'workflow_operations', ['service_collection_id'], unique=False)
    op.create_index('idx_workflow_operations_project_id', 'workflow_operations', ['project_id'], unique=False)
    op.create_index('idx_workflow_operations_requested_by', 'workflow_operations', ['requested_by_id'], unique=False)
    op.create_index('idx_workflow_operations_scheduled', 'workflow_operations', ['scheduled_at'], unique=False)
    op.create_index('idx_workflow_operations_status', 'workflow_operations', ['status'], unique=False)
    op.create_index('idx_workflow_operations_type', 'workflow_operations', ['operation_type'], unique=False)
    op.create_foreign_key(None, 'workflow_operations', 'projects', ['project_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'workflow_operations', type_='foreignkey')
    op.drop_index('idx_workflow_operations_type', table_name='workflow_operations')
    op.drop_index('idx_workflow_operations_status', table_name='workflow_operations')
    op.drop_index('idx_workflow_operations_scheduled', table_name='workflow_operations')
    op.drop_index('idx_workflow_operations_requested_by', table_name='workflow_operations')
    op.drop_index('idx_workflow_operations_project_id', table_name='workflow_operations')
    op.drop_index('idx_workflow_operations_collection_id', table_name='workflow_operations')
    op.drop_index('idx_workflow_operations_assigned_to', table_name='workflow_operations')
    op.drop_column('workflow_operations', 'project_id')
    op.drop_constraint(None, 'service_collections', type_='foreignkey')
    op.drop_column('service_collections', 'project_id')
    op.drop_constraint(None, 'planned_resources', type_='foreignkey')
    op.drop_index('idx_planned_resources_type', table_name='planned_resources')
    op.drop_index('idx_planned_resources_project_id', table_name='planned_resources')
    op.drop_index('idx_planned_resources_name', table_name='planned_resources')
    op.drop_index('idx_planned_resources_collection_id', table_name='planned_resources')
    op.drop_column('planned_resources', 'project_id')
    op.drop_constraint(None, 'managed_resources', type_='foreignkey')
    op.drop_index('idx_managed_resources_vultr_id', table_name='managed_resources')
    op.drop_index('idx_managed_resources_type', table_name='managed_resources')
    op.drop_index('idx_managed_resources_status', table_name='managed_resources')
    op.drop_index('idx_managed_resources_project_id', table_name='managed_resources')
    op.drop_index('idx_managed_resources_name', table_name='managed_resources')
    op.drop_index('idx_managed_resources_collection_id', table_name='managed_resources')
    op.drop_column('managed_resources', 'project_id')
    op.drop_index('idx_project_members_user_id', table_name='project_members')
    op.drop_index('idx_project_members_role', table_name='project_members')
    op.drop_index('idx_project_members_project_id', table_name='project_members')
    op.drop_table('project_members')
    op.drop_index('idx_project_invitations_token', table_name='project_invitations')
    op.drop_index('idx_project_invitations_project_id', table_name='project_invitations')
    op.drop_index('idx_project_invitations_expires_at', table_name='project_invitations')
    op.drop_index('idx_project_invitations_email', table_name='project_invitations')
    op.drop_table('project_invitations')
    op.drop_index('idx_audit_logs_user_id', table_name='project_audit_logs')
    op.drop_index('idx_audit_logs_resource_type', table_name='project_audit_logs')
    op.drop_index('idx_audit_logs_project_id', table_name='project_audit_logs')
    op.drop_index('idx_audit_logs_created_at', table_name='project_audit_logs')
    op.drop_index('idx_audit_logs_action', table_name='project_audit_logs')
    op.drop_table('project_audit_logs')
    op.drop_index('idx_projects_status', table_name='projects')
    op.drop_index('idx_projects_slug', table_name='projects')
    op.drop_index('idx_projects_owner_id', table_name='projects')
    op.drop_table('projects')
    # ### end Alembic commands ###
