"""Complete initial schema with users and all tables

Revision ID: e3d1ec6b7c6a
Revises: 
Create Date: 2025-09-25 23:10:06.535642

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e3d1ec6b7c6a'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('username', sa.String(length=100), nullable=True),
    sa.Column('password_hash', sa.String(length=255), nullable=True),
    sa.Column('oauth_provider', sa.String(length=50), nullable=True),
    sa.Column('oauth_subject', sa.String(length=255), nullable=True),
    sa.Column('first_name', sa.String(length=100), nullable=False),
    sa.Column('last_name', sa.String(length=100), nullable=False),
    sa.Column('display_name', sa.String(length=200), nullable=True),
    sa.Column('avatar_url', sa.String(length=500), nullable=True),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('role', sa.Enum('ADMIN', 'MANAGER', 'DEVELOPER', 'VIEWER', 'SERVICE_ACCOUNT', name='userrole'), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'INACTIVE', 'SUSPENDED', 'PENDING_VERIFICATION', name='userstatus'), nullable=False),
    sa.Column('is_service_account', sa.Boolean(), nullable=True),
    sa.Column('api_key_hash', sa.String(length=255), nullable=True),
    sa.Column('api_key_created_at', sa.DateTime(), nullable=True),
    sa.Column('api_key_last_used', sa.DateTime(), nullable=True),
    sa.Column('preferences', sa.JSON(), nullable=True),
    sa.Column('timezone', sa.String(length=50), nullable=True),
    sa.Column('language', sa.String(length=10), nullable=True),
    sa.Column('last_login_at', sa.DateTime(), nullable=True),
    sa.Column('last_login_ip', sa.String(length=45), nullable=True),
    sa.Column('failed_login_attempts', sa.JSON(), nullable=True),
    sa.Column('global_permissions', sa.JSON(), nullable=True),
    sa.Column('service_collection_memberships', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('verified_at', sa.DateTime(), nullable=True),
    sa.Column('suspended_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('oauth_provider', 'oauth_subject', name='unique_oauth_identity'),
    sa.UniqueConstraint('username')
    )
    op.create_index('idx_users_email', 'users', ['email'], unique=False)
    op.create_index('idx_users_last_login', 'users', ['last_login_at'], unique=False)
    op.create_index('idx_users_oauth', 'users', ['oauth_provider', 'oauth_subject'], unique=False)
    op.create_index('idx_users_role', 'users', ['role'], unique=False)
    op.create_index('idx_users_status', 'users', ['status'], unique=False)
    op.create_table('connected_accounts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('provider_type', sa.Enum('GITHUB', 'GOOGLE', 'MICROSOFT', 'GITLAB', 'BITBUCKET', 'DISCORD', 'SLACK', name='providertype'), nullable=False),
    sa.Column('provider_id', sa.String(length=255), nullable=False),
    sa.Column('provider_username', sa.String(length=255), nullable=True),
    sa.Column('provider_email', sa.String(length=255), nullable=True),
    sa.Column('display_name', sa.String(length=255), nullable=True),
    sa.Column('avatar_url', sa.String(length=500), nullable=True),
    sa.Column('profile_url', sa.String(length=500), nullable=True),
    sa.Column('provider_data', sa.JSON(), nullable=True),
    sa.Column('access_token_hash', sa.Text(), nullable=True),
    sa.Column('refresh_token_hash', sa.Text(), nullable=True),
    sa.Column('token_expires_at', sa.DateTime(), nullable=True),
    sa.Column('token_scope', sa.JSON(), nullable=True),
    sa.Column('is_primary', sa.Boolean(), nullable=True),
    sa.Column('is_verified', sa.Boolean(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('first_connected_at', sa.DateTime(), nullable=False),
    sa.Column('last_used_at', sa.DateTime(), nullable=True),
    sa.Column('last_sync_at', sa.DateTime(), nullable=True),
    sa.Column('connection_count', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('provider_type', 'provider_id', name='unique_provider_account'),
    sa.UniqueConstraint('user_id', 'provider_type', 'is_primary', name='unique_primary_provider')
    )
    op.create_index('idx_connected_accounts_active', 'connected_accounts', ['is_active'], unique=False)
    op.create_index('idx_connected_accounts_last_used', 'connected_accounts', ['last_used_at'], unique=False)
    op.create_index('idx_connected_accounts_provider', 'connected_accounts', ['provider_type', 'provider_id'], unique=False)
    op.create_index('idx_connected_accounts_user', 'connected_accounts', ['user_id'], unique=False)
    op.create_table('passkeys',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('credential_id', sa.String(length=1024), nullable=False),
    sa.Column('public_key', sa.Text(), nullable=False),
    sa.Column('sign_count', sa.JSON(), nullable=True),
    sa.Column('authenticator_type', sa.Enum('PLATFORM', 'CROSS_PLATFORM', name='passkeyauthenticatortype'), nullable=False),
    sa.Column('aaguid', sa.String(length=36), nullable=True),
    sa.Column('transport_methods', sa.JSON(), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('device_info', sa.JSON(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('is_backup_eligible', sa.Boolean(), nullable=True),
    sa.Column('is_backup_state', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('last_used_at', sa.DateTime(), nullable=True),
    sa.Column('usage_count', sa.JSON(), nullable=True),
    sa.Column('last_challenge_at', sa.DateTime(), nullable=True),
    sa.Column('failed_attempts', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('credential_id')
    )
    op.create_index('idx_passkeys_active', 'passkeys', ['is_active'], unique=False)
    op.create_index('idx_passkeys_credential', 'passkeys', ['credential_id'], unique=False)
    op.create_index('idx_passkeys_last_used', 'passkeys', ['last_used_at'], unique=False)
    op.create_index('idx_passkeys_type', 'passkeys', ['authenticator_type'], unique=False)
    op.create_index('idx_passkeys_user', 'passkeys', ['user_id'], unique=False)
    op.create_table('projects',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('slug', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('ACTIVE', 'SUSPENDED', 'ARCHIVED', name='projectstatus'), nullable=False),
    sa.Column('color', sa.String(length=7), nullable=True),
    sa.Column('avatar_url', sa.String(length=512), nullable=True),
    sa.Column('owner_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('settings', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug')
    )
    op.create_index('idx_projects_owner_id', 'projects', ['owner_id'], unique=False)
    op.create_index('idx_projects_slug', 'projects', ['slug'], unique=False)
    op.create_index('idx_projects_status', 'projects', ['status'], unique=False)
    op.create_table('authentication_sessions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('session_token_hash', sa.String(length=255), nullable=False),
    sa.Column('refresh_token_hash', sa.String(length=255), nullable=True),
    sa.Column('device_fingerprint', sa.String(length=255), nullable=True),
    sa.Column('user_agent', sa.Text(), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=False),
    sa.Column('location_data', sa.JSON(), nullable=True),
    sa.Column('login_method', sa.String(length=50), nullable=False),
    sa.Column('provider_type', sa.Enum('GITHUB', 'GOOGLE', 'MICROSOFT', 'GITLAB', 'BITBUCKET', 'DISCORD', 'SLACK', name='providertype'), nullable=True),
    sa.Column('connected_account_id', sa.UUID(), nullable=True),
    sa.Column('passkey_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('last_activity_at', sa.DateTime(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('ended_at', sa.DateTime(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('end_reason', sa.String(length=50), nullable=True),
    sa.Column('is_suspicious', sa.Boolean(), nullable=True),
    sa.Column('security_flags', sa.JSON(), nullable=True),
    sa.Column('request_count', sa.JSON(), nullable=True),
    sa.Column('activity_summary', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['connected_account_id'], ['connected_accounts.id'], ),
    sa.ForeignKeyConstraint(['passkey_id'], ['passkeys.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('session_token_hash')
    )
    op.create_index('idx_auth_sessions_active', 'authentication_sessions', ['is_active', 'expires_at'], unique=False)
    op.create_index('idx_auth_sessions_created', 'authentication_sessions', ['created_at'], unique=False)
    op.create_index('idx_auth_sessions_device', 'authentication_sessions', ['device_fingerprint'], unique=False)
    op.create_index('idx_auth_sessions_ip', 'authentication_sessions', ['ip_address'], unique=False)
    op.create_index('idx_auth_sessions_last_activity', 'authentication_sessions', ['last_activity_at'], unique=False)
    op.create_index('idx_auth_sessions_suspicious', 'authentication_sessions', ['is_suspicious'], unique=False)
    op.create_index('idx_auth_sessions_token', 'authentication_sessions', ['session_token_hash'], unique=False)
    op.create_index('idx_auth_sessions_user', 'authentication_sessions', ['user_id'], unique=False)
    op.create_table('project_audit_logs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('action', sa.String(length=100), nullable=False),
    sa.Column('resource_type', sa.String(length=50), nullable=False),
    sa.Column('resource_id', sa.String(length=255), nullable=True),
    sa.Column('resource_name', sa.String(length=255), nullable=True),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('user_agent', sa.Text(), nullable=True),
    sa.Column('old_values', sa.JSON(), nullable=True),
    sa.Column('new_values', sa.JSON(), nullable=True),
    sa.Column('context_data', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_project_audit_logs_action', 'project_audit_logs', ['action'], unique=False)
    op.create_index('idx_project_audit_logs_created_at', 'project_audit_logs', ['created_at'], unique=False)
    op.create_index('idx_project_audit_logs_project_id', 'project_audit_logs', ['project_id'], unique=False)
    op.create_index('idx_project_audit_logs_resource_type', 'project_audit_logs', ['resource_type'], unique=False)
    op.create_index('idx_project_audit_logs_user_id', 'project_audit_logs', ['user_id'], unique=False)
    op.create_table('project_invitations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('role', sa.Enum('OWNER', 'ADMIN', 'MANAGER', 'DEVELOPER', 'VIEWER', name='projectrole'), nullable=False),
    sa.Column('token', sa.String(length=255), nullable=False),
    sa.Column('accepted', sa.Boolean(), nullable=False),
    sa.Column('accepted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('accepted_by_user_id', sa.UUID(), nullable=True),
    sa.Column('invited_by_user_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['accepted_by_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['invited_by_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('project_id', 'email', name='uq_project_invitation_email'),
    sa.UniqueConstraint('token')
    )
    op.create_index('idx_project_invitations_email', 'project_invitations', ['email'], unique=False)
    op.create_index('idx_project_invitations_expires_at', 'project_invitations', ['expires_at'], unique=False)
    op.create_index('idx_project_invitations_project_id', 'project_invitations', ['project_id'], unique=False)
    op.create_index('idx_project_invitations_token', 'project_invitations', ['token'], unique=False)
    op.create_table('project_members',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('role', sa.Enum('OWNER', 'ADMIN', 'MANAGER', 'DEVELOPER', 'VIEWER', name='projectrole'), nullable=False),
    sa.Column('added_by_user_id', sa.UUID(), nullable=True),
    sa.Column('added_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['added_by_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('project_id', 'user_id', name='uq_project_user')
    )
    op.create_index('idx_project_members_project_id', 'project_members', ['project_id'], unique=False)
    op.create_index('idx_project_members_role', 'project_members', ['role'], unique=False)
    op.create_index('idx_project_members_user_id', 'project_members', ['user_id'], unique=False)
    op.create_table('service_collections',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('environment', sa.Enum('DEVELOPMENT', 'TESTING', 'STAGING', 'PRODUCTION', name='collectionenvironment'), nullable=False),
    sa.Column('status', sa.Enum('DRAFT', 'PENDING_APPROVAL', 'ACTIVE', 'SUSPENDED', 'ARCHIVED', name='collectionstatus'), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('created_by', sa.String(length=255), nullable=False),
    sa.Column('owner_email', sa.String(length=255), nullable=False),
    sa.Column('vultr_service_user', sa.String(length=255), nullable=True),
    sa.Column('allowed_regions', sa.JSON(), nullable=True),
    sa.Column('cost_budget_monthly', sa.String(length=20), nullable=True),
    sa.Column('members', sa.JSON(), nullable=True),
    sa.Column('permissions', sa.JSON(), nullable=True),
    sa.Column('approval_required', sa.Boolean(), nullable=True),
    sa.Column('auto_approve_operations', sa.JSON(), nullable=True),
    sa.Column('restricted_operations', sa.JSON(), nullable=True),
    sa.Column('tags', sa.JSON(), nullable=True),
    sa.Column('configuration', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('archived_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name', 'environment', 'owner_email', name='unique_collection_per_env_owner')
    )
    op.create_index('idx_service_collections_created_by', 'service_collections', ['created_by'], unique=False)
    op.create_index('idx_service_collections_environment', 'service_collections', ['environment'], unique=False)
    op.create_index('idx_service_collections_owner', 'service_collections', ['owner_email'], unique=False)
    op.create_index('idx_service_collections_status', 'service_collections', ['status'], unique=False)
    op.create_table('audit_logs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('action', sa.Enum('LOGIN', 'LOGOUT', 'LOGIN_FAILED', 'PASSWORD_CHANGED', 'API_KEY_CREATED', 'API_KEY_USED', 'PASSKEY_REGISTERED', 'PASSKEY_AUTHENTICATION', 'PASSKEY_DELETED', 'CONNECTED_ACCOUNT_ADDED', 'CONNECTED_ACCOUNT_REMOVED', 'COLLECTION_CREATED', 'COLLECTION_UPDATED', 'COLLECTION_DELETED', 'COLLECTION_ARCHIVED', 'COLLECTION_MEMBER_ADDED', 'COLLECTION_MEMBER_REMOVED', 'COLLECTION_MEMBER_ROLE_CHANGED', 'RESOURCE_PLANNED', 'RESOURCE_CREATED', 'RESOURCE_UPDATED', 'RESOURCE_DELETED', 'RESOURCE_IMPORTED', 'RESOURCE_COST_UPDATED', 'WORKFLOW_OPERATION_CREATED', 'WORKFLOW_OPERATION_STARTED', 'WORKFLOW_OPERATION_COMPLETED', 'WORKFLOW_OPERATION_FAILED', 'WORKFLOW_OPERATION_CANCELLED', 'APPROVAL_REQUESTED', 'APPROVAL_GRANTED', 'APPROVAL_REJECTED', 'APPROVAL_EXPIRED', 'USER_CREATED', 'USER_UPDATED', 'USER_SUSPENDED', 'USER_ACTIVATED', 'USER_ROLE_CHANGED', 'VULTR_API_CALL', 'VULTR_API_ERROR', 'VULTR_RESOURCE_SYNC', 'SYSTEM_STARTUP', 'SYSTEM_SHUTDOWN', 'CONFIGURATION_CHANGED', 'BACKUP_CREATED', 'MIGRATION_EXECUTED', name='auditaction'), nullable=False),
    sa.Column('severity', sa.Enum('DEBUG', 'INFO', 'WARNING', 'ERROR', 'CRITICAL', name='auditseverity'), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('service_collection_id', sa.UUID(), nullable=True),
    sa.Column('session_id', sa.String(length=255), nullable=True),
    sa.Column('request_id', sa.String(length=255), nullable=True),
    sa.Column('correlation_id', sa.String(length=255), nullable=True),
    sa.Column('source_ip', sa.String(length=45), nullable=True),
    sa.Column('user_agent', sa.Text(), nullable=True),
    sa.Column('source_system', sa.String(length=100), nullable=True),
    sa.Column('resource_type', sa.String(length=50), nullable=True),
    sa.Column('resource_id', sa.String(length=255), nullable=True),
    sa.Column('parent_resource_id', sa.String(length=255), nullable=True),
    sa.Column('operation_id', sa.String(length=255), nullable=True),
    sa.Column('vultr_resource_id', sa.String(length=255), nullable=True),
    sa.Column('before_data', sa.JSON(), nullable=True),
    sa.Column('after_data', sa.JSON(), nullable=True),
    sa.Column('audit_metadata', sa.JSON(), nullable=True),
    sa.Column('tags', sa.JSON(), nullable=True),
    sa.Column('category', sa.String(length=50), nullable=True),
    sa.Column('error_code', sa.String(length=50), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('stack_trace', sa.Text(), nullable=True),
    sa.Column('duration_ms', sa.Integer(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('retention_policy', sa.String(length=50), nullable=True),
    sa.Column('is_sensitive', sa.Boolean(), nullable=True),
    sa.Column('is_compliance_relevant', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['service_collection_id'], ['service_collections.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_audit_logs_action', 'audit_logs', ['action'], unique=False)
    op.create_index('idx_audit_logs_category_time', 'audit_logs', ['category', 'timestamp'], unique=False)
    op.create_index('idx_audit_logs_collection_id', 'audit_logs', ['service_collection_id'], unique=False)
    op.create_index('idx_audit_logs_compliance', 'audit_logs', ['is_compliance_relevant', 'timestamp'], unique=False)
    op.create_index('idx_audit_logs_correlation', 'audit_logs', ['correlation_id'], unique=False)
    op.create_index('idx_audit_logs_operation', 'audit_logs', ['operation_id'], unique=False)
    op.create_index('idx_audit_logs_request', 'audit_logs', ['request_id'], unique=False)
    op.create_index('idx_audit_logs_resource', 'audit_logs', ['resource_type', 'resource_id'], unique=False)
    op.create_index('idx_audit_logs_session', 'audit_logs', ['session_id'], unique=False)
    op.create_index('idx_audit_logs_severity', 'audit_logs', ['severity'], unique=False)
    op.create_index('idx_audit_logs_source_ip', 'audit_logs', ['source_ip'], unique=False)
    op.create_index('idx_audit_logs_timestamp', 'audit_logs', ['timestamp'], unique=False)
    op.create_index('idx_audit_logs_user_id', 'audit_logs', ['user_id'], unique=False)
    op.create_table('managed_resources',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('service_collection_id', sa.UUID(), nullable=False),
    sa.Column('vultr_resource_id', sa.String(length=255), nullable=False),
    sa.Column('resource_type', sa.Enum('INSTANCE', 'DOMAIN', 'DNS_RECORD', 'FIREWALL_GROUP', 'FIREWALL_RULE', 'SSH_KEY', 'SNAPSHOT', 'BLOCK_STORAGE', 'LOAD_BALANCER', 'VPC', 'OBJECT_STORAGE', name='resourcetype'), nullable=False),
    sa.Column('resource_name', sa.String(length=255), nullable=False),
    sa.Column('status', sa.Enum('PLANNED', 'CREATING', 'ACTIVE', 'ERROR', 'DELETING', 'DELETED', name='resourcestatus'), nullable=False),
    sa.Column('configuration', sa.JSON(), nullable=True),
    sa.Column('resource_metadata', sa.JSON(), nullable=True),
    sa.Column('monthly_cost', sa.String(length=20), nullable=True),
    sa.Column('last_cost_update', sa.DateTime(), nullable=True),
    sa.Column('managed_by', sa.String(length=255), nullable=False),
    sa.Column('import_source', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('last_sync', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.ForeignKeyConstraint(['service_collection_id'], ['service_collections.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('vultr_resource_id')
    )
    op.create_index('idx_managed_resources_collection_id', 'managed_resources', ['service_collection_id'], unique=False)
    op.create_index('idx_managed_resources_name', 'managed_resources', ['resource_name'], unique=False)
    op.create_index('idx_managed_resources_project_id', 'managed_resources', ['project_id'], unique=False)
    op.create_index('idx_managed_resources_status', 'managed_resources', ['status'], unique=False)
    op.create_index('idx_managed_resources_type', 'managed_resources', ['resource_type'], unique=False)
    op.create_index('idx_managed_resources_vultr_id', 'managed_resources', ['vultr_resource_id'], unique=False)
    op.create_table('planned_resources',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('service_collection_id', sa.UUID(), nullable=False),
    sa.Column('resource_type', sa.Enum('INSTANCE', 'DOMAIN', 'DNS_RECORD', 'FIREWALL_GROUP', 'FIREWALL_RULE', 'SSH_KEY', 'SNAPSHOT', 'BLOCK_STORAGE', 'LOAD_BALANCER', 'VPC', 'OBJECT_STORAGE', name='resourcetype'), nullable=False),
    sa.Column('resource_name', sa.String(length=255), nullable=False),
    sa.Column('resource_config', sa.JSON(), nullable=False),
    sa.Column('depends_on', sa.JSON(), nullable=True),
    sa.Column('estimated_monthly_cost', sa.String(length=20), nullable=True),
    sa.Column('estimated_setup_cost', sa.String(length=20), nullable=True),
    sa.Column('planned_by', sa.String(length=255), nullable=False),
    sa.Column('approved_by', sa.String(length=255), nullable=True),
    sa.Column('approval_required', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('approved_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.ForeignKeyConstraint(['service_collection_id'], ['service_collections.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_planned_resources_collection_id', 'planned_resources', ['service_collection_id'], unique=False)
    op.create_index('idx_planned_resources_name', 'planned_resources', ['resource_name'], unique=False)
    op.create_index('idx_planned_resources_project_id', 'planned_resources', ['project_id'], unique=False)
    op.create_index('idx_planned_resources_type', 'planned_resources', ['resource_type'], unique=False)
    op.create_table('workflow_operations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('operation_type', sa.Enum('CREATE_INSTANCE', 'DELETE_INSTANCE', 'UPDATE_INSTANCE', 'CREATE_DOMAIN', 'DELETE_DOMAIN', 'CREATE_DNS_RECORD', 'UPDATE_DNS_RECORD', 'DELETE_DNS_RECORD', 'CREATE_FIREWALL_RULE', 'DELETE_FIREWALL_RULE', 'START_INSTANCE', 'STOP_INSTANCE', 'REBOOT_INSTANCE', 'SNAPSHOT_INSTANCE', name='operationtype'), nullable=False),
    sa.Column('status', sa.Enum('QUEUED', 'PENDING_APPROVAL', 'APPROVED', 'REJECTED', 'EXECUTING', 'COMPLETED', 'FAILED', 'CANCELLED', name='operationstatus'), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('service_collection_id', sa.UUID(), nullable=False),
    sa.Column('requested_by_id', sa.UUID(), nullable=False),
    sa.Column('assigned_to_id', sa.UUID(), nullable=True),
    sa.Column('request_context', sa.JSON(), nullable=True),
    sa.Column('resource_type', sa.String(length=50), nullable=False),
    sa.Column('resource_config', sa.JSON(), nullable=False),
    sa.Column('depends_on_operations', sa.JSON(), nullable=True),
    sa.Column('blocks_operations', sa.JSON(), nullable=True),
    sa.Column('vultr_resource_id', sa.String(length=255), nullable=True),
    sa.Column('execution_job_id', sa.String(length=255), nullable=True),
    sa.Column('execution_logs', sa.Text(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('estimated_cost_monthly', sa.String(length=20), nullable=True),
    sa.Column('estimated_cost_setup', sa.String(length=20), nullable=True),
    sa.Column('scheduled_at', sa.DateTime(), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['assigned_to_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.ForeignKeyConstraint(['requested_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['service_collection_id'], ['service_collections.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_workflow_operations_assigned_to', 'workflow_operations', ['assigned_to_id'], unique=False)
    op.create_index('idx_workflow_operations_collection_id', 'workflow_operations', ['service_collection_id'], unique=False)
    op.create_index('idx_workflow_operations_project_id', 'workflow_operations', ['project_id'], unique=False)
    op.create_index('idx_workflow_operations_requested_by', 'workflow_operations', ['requested_by_id'], unique=False)
    op.create_index('idx_workflow_operations_scheduled', 'workflow_operations', ['scheduled_at'], unique=False)
    op.create_index('idx_workflow_operations_status', 'workflow_operations', ['status'], unique=False)
    op.create_index('idx_workflow_operations_type', 'workflow_operations', ['operation_type'], unique=False)
    op.create_table('approval_requests',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('workflow_operation_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'APPROVED', 'REJECTED', 'EXPIRED', name='approvalstatus'), nullable=False),
    sa.Column('approver_email', sa.String(length=255), nullable=False),
    sa.Column('approval_reason', sa.Text(), nullable=True),
    sa.Column('business_justification', sa.Text(), nullable=True),
    sa.Column('risk_assessment', sa.JSON(), nullable=True),
    sa.Column('decision', sa.String(length=20), nullable=True),
    sa.Column('decision_reason', sa.Text(), nullable=True),
    sa.Column('decided_by', sa.String(length=255), nullable=True),
    sa.Column('decided_at', sa.DateTime(), nullable=True),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['workflow_operation_id'], ['workflow_operations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('approval_requests')
    op.drop_index('idx_workflow_operations_type', table_name='workflow_operations')
    op.drop_index('idx_workflow_operations_status', table_name='workflow_operations')
    op.drop_index('idx_workflow_operations_scheduled', table_name='workflow_operations')
    op.drop_index('idx_workflow_operations_requested_by', table_name='workflow_operations')
    op.drop_index('idx_workflow_operations_project_id', table_name='workflow_operations')
    op.drop_index('idx_workflow_operations_collection_id', table_name='workflow_operations')
    op.drop_index('idx_workflow_operations_assigned_to', table_name='workflow_operations')
    op.drop_table('workflow_operations')
    op.drop_index('idx_planned_resources_type', table_name='planned_resources')
    op.drop_index('idx_planned_resources_project_id', table_name='planned_resources')
    op.drop_index('idx_planned_resources_name', table_name='planned_resources')
    op.drop_index('idx_planned_resources_collection_id', table_name='planned_resources')
    op.drop_table('planned_resources')
    op.drop_index('idx_managed_resources_vultr_id', table_name='managed_resources')
    op.drop_index('idx_managed_resources_type', table_name='managed_resources')
    op.drop_index('idx_managed_resources_status', table_name='managed_resources')
    op.drop_index('idx_managed_resources_project_id', table_name='managed_resources')
    op.drop_index('idx_managed_resources_name', table_name='managed_resources')
    op.drop_index('idx_managed_resources_collection_id', table_name='managed_resources')
    op.drop_table('managed_resources')
    op.drop_index('idx_audit_logs_user_id', table_name='audit_logs')
    op.drop_index('idx_audit_logs_timestamp', table_name='audit_logs')
    op.drop_index('idx_audit_logs_source_ip', table_name='audit_logs')
    op.drop_index('idx_audit_logs_severity', table_name='audit_logs')
    op.drop_index('idx_audit_logs_session', table_name='audit_logs')
    op.drop_index('idx_audit_logs_resource', table_name='audit_logs')
    op.drop_index('idx_audit_logs_request', table_name='audit_logs')
    op.drop_index('idx_audit_logs_operation', table_name='audit_logs')
    op.drop_index('idx_audit_logs_correlation', table_name='audit_logs')
    op.drop_index('idx_audit_logs_compliance', table_name='audit_logs')
    op.drop_index('idx_audit_logs_collection_id', table_name='audit_logs')
    op.drop_index('idx_audit_logs_category_time', table_name='audit_logs')
    op.drop_index('idx_audit_logs_action', table_name='audit_logs')
    op.drop_table('audit_logs')
    op.drop_index('idx_service_collections_status', table_name='service_collections')
    op.drop_index('idx_service_collections_owner', table_name='service_collections')
    op.drop_index('idx_service_collections_environment', table_name='service_collections')
    op.drop_index('idx_service_collections_created_by', table_name='service_collections')
    op.drop_table('service_collections')
    op.drop_index('idx_project_members_user_id', table_name='project_members')
    op.drop_index('idx_project_members_role', table_name='project_members')
    op.drop_index('idx_project_members_project_id', table_name='project_members')
    op.drop_table('project_members')
    op.drop_index('idx_project_invitations_token', table_name='project_invitations')
    op.drop_index('idx_project_invitations_project_id', table_name='project_invitations')
    op.drop_index('idx_project_invitations_expires_at', table_name='project_invitations')
    op.drop_index('idx_project_invitations_email', table_name='project_invitations')
    op.drop_table('project_invitations')
    op.drop_index('idx_project_audit_logs_user_id', table_name='project_audit_logs')
    op.drop_index('idx_project_audit_logs_resource_type', table_name='project_audit_logs')
    op.drop_index('idx_project_audit_logs_project_id', table_name='project_audit_logs')
    op.drop_index('idx_project_audit_logs_created_at', table_name='project_audit_logs')
    op.drop_index('idx_project_audit_logs_action', table_name='project_audit_logs')
    op.drop_table('project_audit_logs')
    op.drop_index('idx_auth_sessions_user', table_name='authentication_sessions')
    op.drop_index('idx_auth_sessions_token', table_name='authentication_sessions')
    op.drop_index('idx_auth_sessions_suspicious', table_name='authentication_sessions')
    op.drop_index('idx_auth_sessions_last_activity', table_name='authentication_sessions')
    op.drop_index('idx_auth_sessions_ip', table_name='authentication_sessions')
    op.drop_index('idx_auth_sessions_device', table_name='authentication_sessions')
    op.drop_index('idx_auth_sessions_created', table_name='authentication_sessions')
    op.drop_index('idx_auth_sessions_active', table_name='authentication_sessions')
    op.drop_table('authentication_sessions')
    op.drop_index('idx_projects_status', table_name='projects')
    op.drop_index('idx_projects_slug', table_name='projects')
    op.drop_index('idx_projects_owner_id', table_name='projects')
    op.drop_table('projects')
    op.drop_index('idx_passkeys_user', table_name='passkeys')
    op.drop_index('idx_passkeys_type', table_name='passkeys')
    op.drop_index('idx_passkeys_last_used', table_name='passkeys')
    op.drop_index('idx_passkeys_credential', table_name='passkeys')
    op.drop_index('idx_passkeys_active', table_name='passkeys')
    op.drop_table('passkeys')
    op.drop_index('idx_connected_accounts_user', table_name='connected_accounts')
    op.drop_index('idx_connected_accounts_provider', table_name='connected_accounts')
    op.drop_index('idx_connected_accounts_last_used', table_name='connected_accounts')
    op.drop_index('idx_connected_accounts_active', table_name='connected_accounts')
    op.drop_table('connected_accounts')
    op.drop_index('idx_users_status', table_name='users')
    op.drop_index('idx_users_role', table_name='users')
    op.drop_index('idx_users_oauth', table_name='users')
    op.drop_index('idx_users_last_login', table_name='users')
    op.drop_index('idx_users_email', table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
